version: '2.2'

services:
    web:
        image: nginx:stable
        ports:
            - "127.0.0.1:58080:80"
        #- "58080:80"
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "./web:/usr/share/nginx/frontend:ro"
            - "./backend:/usr/share/nginx/backend:ro"
        restart: always
        depends_on:
            - php
            - mysql
        environment:
            - "VIRTUAL_HOST=blog.entroy.tk"

    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile_php-fpm
        restart: always
        volumes:
            - "./web:/usr/share/nginx/frontend:ro"
            - "./backend:/usr/share/nginx/backend:ro"
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini:ro"

    mysql:
        image: mariadb:10.7.1-focal
        volumes:
            - "./database/data:/var/lib/mysql"
            #- "/tmp/database/data:/var/lib/mysql"
            - "./database/init:/docker-entrypoint-initdb.d:ro"
            - "./etc/mysql/conf.d:/etc/mysql/conf.d:ro"
        restart: always
        environment:
            LANG: C.UTF-8
            MYSQL_ROOT_PASSWORD: 275d844a4b7995b572a1e6764dd3b797d4b4818d613f0ff0b1fb8771b65dcbe7
            MYSQL_DATABASE: web
            MYSQL_USER: web_user
            MYSQL_PASSWORD: ac5d79638d4d8020309095b98819f35d29ca90affa61456a208313301805e4d8
        command: mysqld --max_statement_time=2

networks:
    default:
        external:
            name: bridge-network